# 认识numpy 和 pandas 

## 区别
- numpy 主要使用array类，它的矩阵计算十分强大；
- pandas 主要使用DataFrame（实际上是ndarray）类，这个类用来管理数据。

In [15]:
import pandas as pd
import numpy as np

# 列表
sample_array = np.array([1,2,3,4,5])
sample_array

# 对数组进行的运算会作用到数组的每个元素上
sample_array + 2

# 如果放置不同类型的数据，那么它就会有小情绪
# 就会变成字符串
np.array([1, 2, "Q"])

# 二维数组
sample_array_2 = np.array(
    [[1,2,3,4,5],
    [6,7,8, 9, 10]]
)
sample_array_2

# 行数和列数
sample_array_2.shape


(2, 5)

- 等差数列

In [16]:
import pandas as pd
import numpy as np

#  等差数列
# 其实range 和 arange还是有很大的区别的
np.arange(start = 1, stop = 6, step = 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8])

- 多种生成数组的方式

In [17]:
np.tile("A", 5)
np.tile(0, 4)
# 生成只有0的数组
np.zeros(4)
np.zeros([2,3])
# 生成只有1的数组
np.ones(3)

array([1., 1., 1.])

-   切片(slice)

In [18]:
import pandas as pd
import numpy as np
d1_array = np.array([1,2,3,4,5])
d1_array
d1_array[1:3]
d2_array = np.array(
    [[1,2,3,4,5],
    [6,7,8,9,10]]
)
d2_array
d2_array[0,3]
d2_array[1, 2:4]

array([8, 9])

### 数据帧(DataFrame)

In [19]:
import pandas as pd
import numpy as np
sample_df = pd.DataFrame({
    'col1' : sample_array,
    'col2' : sample_array * 2,
    'clo3' : ["A", "B", "C", "D", "E"]
})
sample_df
# print(sample_df)
# 数据帧的列操作，点操作符
# print(sample_df.col2)
# 这个和下面的是一致的，方括号操作符
# print(sample_df["col2"])
print(sample_df[["col2","clo3"]])
# 删除指定的列
print(sample_df.drop("col1",axis=1))

   col2 clo3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E
   col2 clo3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


### 连接数据帧

In [30]:
import pandas as pd
import numpy as np
df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(["A","B","C"])
})
df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(["D","E","F"])
})
print(pd.concat([df_1, df_2]))
# 横向连接
temp = pd.concat([df_1, df_2], axis=1)

print(temp)

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F
   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F
